# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EFxWxnrQ0usou8Rpf6O1CO16ztkaAXSv
"""

A = int(input())
B = int(input())
if A < B:
    for i in range(A, B + 1):
        print(i)
else:
    for i in range(A, B - 1, -1):
        print(i)



a = int(input())
b = int(input())
a1 = a // 1000
b1 = a // 100 % 10
while (((a1 * 10 + b1) * 10 + b1) * 10 + a1) <= b:
    print(a1, b1, b1, a1, sep="")
    b1 = b1 + 1
    if ( b1 > 9):
        a1 = a1 + 1
        b1 = 0